# Generated by Django 3.1.4 on 2020-12-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_scan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btscan',
            name='bt_mac_addr',
            field=models.TextField(unique=True),
        ),
    ]
