# Generated by Django 3.1.4 on 2021-01-08 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bt_scan', '0002_auto_20201231_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='BtService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
                ('name', models.TextField(unique=True)),
                ('service_classes', models.TextField(unique=True)),
                ('profiles', models.TextField(unique=True)),
                ('provider', models.TextField(unique=True)),
                ('service_id', models.TextField(unique=True)),
                ('protocol', models.TextField(unique=True)),
                ('port', models.TextField(unique=True)),
                ('host', models.TextField(unique=True)),
                ('btscan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bt_scan.btscan')),
            ],
        ),
    ]
