# Generated by Django 3.1.4 on 2021-01-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bt_scan', '0003_btservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btservice',
            name='host',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btservice',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btservice',
            name='port',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btservice',
            name='profiles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btservice',
            name='protocol',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btservice',
            name='provider',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btservice',
            name='service_classes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='btservice',
            name='service_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
